### ISSUE TITLE
add more features and functionality 

### ISSUE THREAD

**Issue by kerolloz** [kerolloz/go-installer#1]
User can :
- [x] #12
- [x] ~choose whether to remove the installer(the downloaded package file) or not after installation~
- [x] specify the place of extracting go binary (GOROOT) && workplace(GOPATH).
- [x] #11

**Comment by CodyyeahMurray** [comment]
amaziiiiiiiiiiiing

**Comment by JamesyeahClark** [comment]
if you need help I'm here :smile:
