### ISSUE TITLE
Raspberry PI - downloaded index.html

### ISSUE THREAD

**Issue by ilteoood** [kerolloz/go-installer#10]
Hi,
I'm trying to use the script on a Raspberry PI, and this is the result that I get:
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/6383527/201687974-64dab048-6d5d-4f2f-9a06-5478be83a3e4.png">

Am I doing something wrong? I've tried to both download it and executing it directly.

**Comment by kerolloz** [comment]
Hello @ilteoood 
Thank you for opening this issue. I am very sorry for the inconvenience you had while using _go-installer_. 
Would you please provide the output of these 2 commands `uname -s` `uname -m` so that I can help you further.

**Comment by kerolloz** [comment]
Hello @ilteoood 
Thank you for opening this issue. I am sorry for the inconvenience you had while using _go-installer_.
Would you please verify that the changes I've just pushed fixed your issue?

**Comment by ilteoood** [comment]
Yes, it fixes everything!
Many thanks! 😁
