### ISSUE TITLE
Broken installation

### ISSUE THREAD

**Issue by SharkFourSix** [kerolloz/go-installer#15]
Installing without root shows fails and asks for root.

Running with sudo installs to /root/ making it inaccessible to other users.

**Comment by kerolloz** [comment]
Hello @SharkFourSix
Thank you for sharing the issue and sorry for your inconvenience.

Would you please share more details with me?
```bash
# What's your output for
uname -a
```

- What method did you use to run the script?
- Does the user that you used to run the command have the required permissions?

**Comment by SharkFourSix** [comment]
I found what the issue was.

Do not export $GOROOT, only $GOPATH, and only if necessary.

The reason it was failing was because goroot and gopath were pointing to the same directory so the installation script was failing to move/delete files.

**Comment by kerolloz** [comment]
Great. Should we close the issue then?

**Comment by SharkFourSix** [comment]
Yes please. Sorry forgot to do that
