### ISSUE TITLE
Option to remove tar.gz after install?

### ISSUE THREAD

**Issue by jeffhertzler** [kerolloz/go-installer#17]
Are you open to adding an option to clean up the downloaded artifact or do this by default?

It's **_ever so slightly_** annoying to have to do this manually after a new version gets installed.

**Comment by kerolloz** [comment]
Hello @jeffhertzler 
Thank you for the feedback. I really wanted to implement this feature for some time but I was just lazy to write those couple of lines 😅. It removes the downloaded package file now by default.
