### ISSUE TITLE
go-installer fail install on VPS ubuntu x86_64 

### ISSUE THREAD

**Issue by ingnelson** [kerolloz/go-installer#7]
Hello .

I get this error : 

![image](https://user-images.githubusercontent.com/6626845/87337061-10c15900-c500-11ea-9def-0c15ab7d60c1.png)

What can i do ?

**Comment by kerolloz** [comment]
Hello @ingnelson 
I am very sorry for the late response. 
I have just seen the issue by chance. 
The issue has been fixed!
