### ISSUE TITLE
go version 1.16

### ISSUE THREAD

**Issue by theblackturtle** [kerolloz/go-installer#8]
Hi, I latest version of go is 1.16 which means the current version regex is not working with it. Can you fix it please? Thanks.

**Comment by kerolloz** [comment]
![image](https://user-images.githubusercontent.com/36763164/113512572-86c19080-9565-11eb-91b6-a6f7cdb2cbca.png)

Do you still have a problem @theblackturtle ?

**Comment by theblackturtle** [comment]
Hi @kerolloz, 
Go Team released the next version (1.16.x) so the script working again. But the bug still there if the go version is `1.17`, `1.18`,...
